name: cloud_mm_vdo_short
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3 #for state management
  get_it: ^7.2.0 #for dependency injection
  flutter_screenutil: ^5.5.3+2 #for responsive UI
  get: ^4.6.5 #FOR route handling
  video_player: ^2.4.2 #vidoe player
  cached_network_image: ^3.2.1 #for network image
  marquee: ^2.2.2 #marqueen text
  firebase_storage: ^10.2.17
  cloud_firestore: ^3.1.17
  image_picker: ^0.8.5+3
  firebase_core: ^1.17.1
  uuid: ^3.0.6
  pull_to_refresh: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
